//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public int LevelId { get; set; }
        public string Title { get; set; }
        public string Lyrics { get; set; }
        public string Contents { get; set; }
        public string SoundPath { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<double> Length { get; set; }
        public string TitleTwo { get; set; }
        public string LengthString { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Level Level { get; set; }
    }
}
