//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HskkQuestion
    {
        public int Id { get; set; }
        public Nullable<double> Sort { get; set; }
        public Nullable<int> HskkId { get; set; }
        public string Image { get; set; }
        public string Audio { get; set; }
        public string TextCN { get; set; }
        public string TextPY { get; set; }
    
        public virtual Hskk Hskk { get; set; }
    }
}
