//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hskk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hskk()
        {
            this.HskkQuestion = new HashSet<HskkQuestion>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> Part { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public Nullable<int> Visible { get; set; }
        public Nullable<int> Category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HskkQuestion> HskkQuestion { get; set; }
    }
}
