//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NimUserEx
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public string Sign { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Ex { get; set; }
        public string Country { get; set; }
        public string Language { get; set; }
        public string Job { get; set; }
        public string About { get; set; }
        public string Voice { get; set; }
        public Nullable<int> Coins { get; set; }
        public Nullable<double> Score { get; set; }
        public string School { get; set; }
    
        public virtual NimUser NimUser { get; set; }
    }
}
