//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudyOnlineEntities : DbContext
    {
        public StudyOnlineEntities()
            : base("name=StudyOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<Folder> Folder { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Level> Level { get; set; }
        public virtual DbSet<NimUser> NimUser { get; set; }
        public virtual DbSet<NimUserEx> NimUserEx { get; set; }
        public virtual DbSet<UploadFile> UploadFile { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Theme> Theme { get; set; }
        public virtual DbSet<CallLog> CallLog { get; set; }
        public virtual DbSet<LogTheme> LogTheme { get; set; }
        public virtual DbSet<Android> Android { get; set; }
        public virtual DbSet<HskLevel> HskLevel { get; set; }
        public virtual DbSet<Recharge> Recharge { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
    }
}
