//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudyOnlineEntities : DbContext
    {
        public StudyOnlineEntities()
            : base("name=StudyOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Android> Android { get; set; }
        public virtual DbSet<AuthCode> AuthCode { get; set; }
        public virtual DbSet<CallLog> CallLog { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<Folder> Folder { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<HsLevel> HsLevel { get; set; }
        public virtual DbSet<Level> Level { get; set; }
        public virtual DbSet<LogTheme> LogTheme { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Member_User> Member_User { get; set; }
        public virtual DbSet<NimUser> NimUser { get; set; }
        public virtual DbSet<NimUserEx> NimUserEx { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Teacherreginfo> Teacherreginfo { get; set; }
        public virtual DbSet<Theme> Theme { get; set; }
        public virtual DbSet<UploadFile> UploadFile { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<X_Menu> X_Menu { get; set; }
        public virtual DbSet<X_Role> X_Role { get; set; }
        public virtual DbSet<X_User> X_User { get; set; }
        public virtual DbSet<View_Document> View_Document { get; set; }
        public virtual DbSet<View_User> View_User { get; set; }
        public virtual DbSet<View_Folder_Member_User> View_Folder_Member_User { get; set; }
        public virtual DbSet<View_Chat_user> View_Chat_user { get; set; }
        public virtual DbSet<View_UserLeftJoinMember> View_UserLeftJoinMember { get; set; }
        public virtual DbSet<Hskk> Hskk { get; set; }
        public virtual DbSet<HskkQuestion> HskkQuestion { get; set; }
        public virtual DbSet<View_Folder_LeftJoin_MemberFolder> View_Folder_LeftJoin_MemberFolder { get; set; }
        public virtual DbSet<View_Document_Lite> View_Document_Lite { get; set; }
        public virtual DbSet<Playlist> Playlist { get; set; }
        public virtual DbSet<ChatData> ChatData { get; set; }
        public virtual DbSet<View_Document_PlayCount> View_Document_PlayCount { get; set; }
    }
}
