//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int Id { get; set; }
        public int Category { get; set; }
        public Nullable<int> IsOnline { get; set; }
        public Nullable<int> IsAvailable { get; set; }
        public Nullable<long> LastRefresh { get; set; }
        public Nullable<long> EnqueueTime { get; set; }
    
        public virtual NimUser NimUser { get; set; }
    }
}
