//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadFile
    {
        public int Id { get; set; }
        public double Size { get; set; }
        public string Path { get; set; }
        public string Info { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string Extension { get; set; }
        public string VersionName { get; set; }
    }
}
