//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Document
    {
        public int LevelId { get; set; }
        public string LevelName { get; set; }
        public Nullable<int> ShowBrowser { get; set; }
        public int FolderId { get; set; }
        public string FolderName { get; set; }
        public int DocumentId { get; set; }
        public string Title { get; set; }
        public string SoundPath { get; set; }
        public Nullable<int> AuditCase { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
    }
}
