//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Chat_user
    {
        public string Id { get; set; }
        public int Source { get; set; }
        public string Student { get; set; }
        public int Target { get; set; }
        public string Teacher { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Finish { get; set; }
        public Nullable<long> ChatId { get; set; }
        public Nullable<int> ChatType { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> BalanceS { get; set; }
        public Nullable<int> Coins { get; set; }
    }
}
