//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_User
    {
        public int Id { get; set; }
        public string Accid { get; set; }
        public string Username { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> IsOnline { get; set; }
        public Nullable<int> IsEnable { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Email { get; set; }
        public string Nickname { get; set; }
        public string Avatar { get; set; }
        public string Country { get; set; }
        public Nullable<int> Coins { get; set; }
    }
}
